apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  labels:
    app: cart-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: asia-south1-docker.pkg.dev/citric-kit-489316-g6/kalaiartifactrepo15/cart-service:latest
        ports:
        - containerPort: 5002
        env:
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:5001"
        - name: PAYMENT_SERVICE_URL
          value: "http://payment-service:5003"
        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app: cart-service
  ports:
    - port: 5002
      targetPort: 5002
  type: ClusterIP